### ISSUE TITLE
plusgroup missing from SAM2FLStock

### ISSUE THREAD

**Issue by marchtaylor** [shfischer/FLfse#3]
Hi Simon,

We just noticed that the FLStock output from SAM2FLStock didn't have the plusgroup defined. I tried this on your example and find the same:

```
library(FLfse)
fit <- FLR_SAM(stk = cod4_stk, idx = cod4_idx, conf = cod4_conf_sam)
stk <- SAM2FLStock(fit)
range(stk)
# min       max plusgroup   minyear   maxyear   minfbar   maxfbar 
#   1         6        NA      1963      2018         2         4 
```

I think this would provide the information about whether this should be defined or not: `fit$conf$maxAgePlusGroup`

Thanks,
Marc

**Comment by shfischer** [comment]
Thanks for comment. Fixed with commit 3f8bfddb64af64a5311c992f08dc1f66e58b957b
